[package]

name = "git_submit"
version = "0.0.1"
authors = ["Thomas Gummerer <t.gummerer@gmail.com>"]

[dependencies]

git2 = "0.3"
tempdir = "0.3"
regex = "0.1"
getopts = "0.2"
hyper = "0.7"
email = "0.0"
